# Generated by Django 3.1.3 on 2021-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=200)),
            ],
        ),
    ]
